// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: proto/center_server.proto

package command

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//注册服务
type ServerRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serverid   int32  `protobuf:"varint,1,opt,name=serverid,proto3" json:"serverid,omitempty"`
	Servertype int32  `protobuf:"varint,2,opt,name=servertype,proto3" json:"servertype,omitempty"`
	Servername string `protobuf:"bytes,3,opt,name=servername,proto3" json:"servername,omitempty"`
	Serveraddr string `protobuf:"bytes,4,opt,name=serveraddr,proto3" json:"serveraddr,omitempty"`
	Isopen     bool   `protobuf:"varint,5,opt,name=isopen,proto3" json:"isopen,omitempty"`
}

func (x *ServerRegisterReq) Reset() {
	*x = ServerRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_center_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegisterReq) ProtoMessage() {}

func (x *ServerRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegisterReq.ProtoReflect.Descriptor instead.
func (*ServerRegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_center_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerRegisterReq) GetServerid() int32 {
	if x != nil {
		return x.Serverid
	}
	return 0
}

func (x *ServerRegisterReq) GetServertype() int32 {
	if x != nil {
		return x.Servertype
	}
	return 0
}

func (x *ServerRegisterReq) GetServername() string {
	if x != nil {
		return x.Servername
	}
	return ""
}

func (x *ServerRegisterReq) GetServeraddr() string {
	if x != nil {
		return x.Serveraddr
	}
	return ""
}

func (x *ServerRegisterReq) GetIsopen() bool {
	if x != nil {
		return x.Isopen
	}
	return false
}

type ServerRegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ServerRegisterResp) Reset() {
	*x = ServerRegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_center_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegisterResp) ProtoMessage() {}

func (x *ServerRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegisterResp.ProtoReflect.Descriptor instead.
func (*ServerRegisterResp) Descriptor() ([]byte, []int) {
	return file_proto_center_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerRegisterResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ServerOpenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serverid int32 `protobuf:"varint,1,opt,name=serverid,proto3" json:"serverid,omitempty"`
	Isopen   bool  `protobuf:"varint,2,opt,name=isopen,proto3" json:"isopen,omitempty"`
}

func (x *ServerOpenReq) Reset() {
	*x = ServerOpenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_center_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerOpenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerOpenReq) ProtoMessage() {}

func (x *ServerOpenReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerOpenReq.ProtoReflect.Descriptor instead.
func (*ServerOpenReq) Descriptor() ([]byte, []int) {
	return file_proto_center_server_proto_rawDescGZIP(), []int{2}
}

func (x *ServerOpenReq) GetServerid() int32 {
	if x != nil {
		return x.Serverid
	}
	return 0
}

func (x *ServerOpenReq) GetIsopen() bool {
	if x != nil {
		return x.Isopen
	}
	return false
}

type ServerOnlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serverid int32 `protobuf:"varint,1,opt,name=serverid,proto3" json:"serverid,omitempty"`
	Num      int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ServerOnlineReq) Reset() {
	*x = ServerOnlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_center_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerOnlineReq) ProtoMessage() {}

func (x *ServerOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_center_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerOnlineReq.ProtoReflect.Descriptor instead.
func (*ServerOnlineReq) Descriptor() ([]byte, []int) {
	return file_proto_center_server_proto_rawDescGZIP(), []int{3}
}

func (x *ServerOnlineReq) GetServerid() int32 {
	if x != nil {
		return x.Serverid
	}
	return 0
}

func (x *ServerOnlineReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_proto_center_server_proto protoreflect.FileDescriptor

var file_proto_center_server_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x22, 0xa7, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x61, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x6f, 0x70, 0x65, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x6f, 0x70, 0x65, 0x6e, 0x22, 0x2c,
	0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x43, 0x0a, 0x0d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x6f,
	0x70, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x6f, 0x70, 0x65,
	0x6e, 0x22, 0x3f, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_center_server_proto_rawDescOnce sync.Once
	file_proto_center_server_proto_rawDescData = file_proto_center_server_proto_rawDesc
)

func file_proto_center_server_proto_rawDescGZIP() []byte {
	file_proto_center_server_proto_rawDescOnce.Do(func() {
		file_proto_center_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_center_server_proto_rawDescData)
	})
	return file_proto_center_server_proto_rawDescData
}

var file_proto_center_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_center_server_proto_goTypes = []interface{}{
	(*ServerRegisterReq)(nil),  // 0: command.ServerRegisterReq
	(*ServerRegisterResp)(nil), // 1: command.ServerRegisterResp
	(*ServerOpenReq)(nil),      // 2: command.ServerOpenReq
	(*ServerOnlineReq)(nil),    // 3: command.ServerOnlineReq
}
var file_proto_center_server_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_center_server_proto_init() }
func file_proto_center_server_proto_init() {
	if File_proto_center_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_center_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_center_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_center_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerOpenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_center_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerOnlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_center_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_center_server_proto_goTypes,
		DependencyIndexes: file_proto_center_server_proto_depIdxs,
		MessageInfos:      file_proto_center_server_proto_msgTypes,
	}.Build()
	File_proto_center_server_proto = out.File
	file_proto_center_server_proto_rawDesc = nil
	file_proto_center_server_proto_goTypes = nil
	file_proto_center_server_proto_depIdxs = nil
}
