package command

const (
	CMD_TICKING = 0x00				//心跳

	ACT_TICKING_REQ = 0x01
	ACT_TICKING_RESP= 0x02

	CMD_RIGSTER_SERVER = 0x01		//注册			

	ACT_RIGSTER_SERVER_REQ = 0x01
	ACT_RIGSTER_SERVER_RESP = 0x02
)

const (
	CMD_USER_MAIN = 0x01

	ACT_USER_REGISTER_REQ = 0x01
	ACT_USER_REGISTER_RESP = 0x02

	ACT_USER_LOGIN_REQ = 0x03
	ACT_USER_LOGIN_RESP = 0x04
)