// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: proto/user_front.proto

package command

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AccountRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accname     string `protobuf:"bytes,1,opt,name=accname,proto3" json:"accname,omitempty"`
	Accpassword string `protobuf:"bytes,2,opt,name=accpassword,proto3" json:"accpassword,omitempty"`
	Fromtype    int32  `protobuf:"varint,3,opt,name=fromtype,proto3" json:"fromtype,omitempty"`
}

func (x *AccountRegisterReq) Reset() {
	*x = AccountRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_front_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRegisterReq) ProtoMessage() {}

func (x *AccountRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_front_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRegisterReq.ProtoReflect.Descriptor instead.
func (*AccountRegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_user_front_proto_rawDescGZIP(), []int{0}
}

func (x *AccountRegisterReq) GetAccname() string {
	if x != nil {
		return x.Accname
	}
	return ""
}

func (x *AccountRegisterReq) GetAccpassword() string {
	if x != nil {
		return x.Accpassword
	}
	return ""
}

func (x *AccountRegisterReq) GetFromtype() int32 {
	if x != nil {
		return x.Fromtype
	}
	return 0
}

type AccountRegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Userid int64 `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Gold   int64 `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	Level  int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp    int32 `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *AccountRegisterResp) Reset() {
	*x = AccountRegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_front_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRegisterResp) ProtoMessage() {}

func (x *AccountRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_front_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRegisterResp.ProtoReflect.Descriptor instead.
func (*AccountRegisterResp) Descriptor() ([]byte, []int) {
	return file_proto_user_front_proto_rawDescGZIP(), []int{1}
}

func (x *AccountRegisterResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AccountRegisterResp) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *AccountRegisterResp) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *AccountRegisterResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AccountRegisterResp) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_proto_user_front_proto protoreflect.FileDescriptor

var file_proto_user_front_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x72, 0x6f,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x22, 0x6c, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x81, 0x01, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x65, 0x78, 0x70, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_front_proto_rawDescOnce sync.Once
	file_proto_user_front_proto_rawDescData = file_proto_user_front_proto_rawDesc
)

func file_proto_user_front_proto_rawDescGZIP() []byte {
	file_proto_user_front_proto_rawDescOnce.Do(func() {
		file_proto_user_front_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_front_proto_rawDescData)
	})
	return file_proto_user_front_proto_rawDescData
}

var file_proto_user_front_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_front_proto_goTypes = []interface{}{
	(*AccountRegisterReq)(nil),  // 0: command.AccountRegisterReq
	(*AccountRegisterResp)(nil), // 1: command.AccountRegisterResp
}
var file_proto_user_front_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_front_proto_init() }
func file_proto_user_front_proto_init() {
	if File_proto_user_front_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_front_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_front_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_front_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_front_proto_goTypes,
		DependencyIndexes: file_proto_user_front_proto_depIdxs,
		MessageInfos:      file_proto_user_front_proto_msgTypes,
	}.Build()
	File_proto_user_front_proto = out.File
	file_proto_user_front_proto_rawDesc = nil
	file_proto_user_front_proto_goTypes = nil
	file_proto_user_front_proto_depIdxs = nil
}
